version: "3.3"
services:
  broker:
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    volumes:
      - ./data:/var/lib/rabbitmq
      - ./log:/var/log/rabbitmq
